class StatsController < ApplicationController
def index
@matches = Match.all
@wins = Match.where("outcome = '1'")
@losses = Match.where("outcome = '0'")

@recent_matches = Match.order(created_at: :desc).limit(20)

@druid_matches = Match.where("user_class = '1'")
@druid_wins = Match.where("user_class = '1' AND outcome = '1'")
@druid_losses = Match.where("user_class = '1' AND outcome = '0'")
@hunter_matches = Match.where("user_class = '2'")
@hunter_wins = Match.where("user_class = '2' AND outcome = '1'")
@hunter_losses = Match.where("user_class = '2' AND outcome = '0'")
@mage_matches = Match.where("user_class = '3'")
@mage_wins = Match.where("user_class = '3' AND outcome = '1'")
@mage_losses = Match.where("user_class = '3' AND outcome = '0'")
@paladin_matches = Match.where("user_class = '4'")
@paladin_wins = Match.where("user_class = '4' AND outcome = '1'")
@paladin_losses = Match.where("user_class = '4' AND outcome = '0'")
@priest_matches = Match.where("user_class = '5'")
@priest_wins = Match.where("user_class = '5' AND outcome = '1'")
@priest_losses = Match.where("user_class = '5' AND outcome = '0'")
@rogue_matches = Match.where("user_class = '6'")
@rogue_wins = Match.where("user_class = '6' AND outcome = '1'")
@rogue_losses = Match.where("user_class = '6' AND outcome = '0'")
@shaman_matches = Match.where("user_class = '7'")
@shaman_wins = Match.where("user_class = '7' AND outcome = '1'")
@shaman_losses = Match.where("user_class = '7' AND outcome = '0'")
@warlock_matches = Match.where("user_class = '8'")
@warlock_wins = Match.where("user_class = '8' AND outcome = '1'")
@warlock_losses = Match.where("user_class = '8' AND outcome = '0'")
@warrior_matches = Match.where("user_class = '9'")
@warrior_wins = Match.where("user_class = '9' AND outcome = '1'")
@warrior_losses = Match.where("user_class = '9' AND outcome = '0'")

@opp_druid_matches = Match.where("opp_class = '1'")
@opp_druid_wins = Match.where("opp_class = '1' AND outcome = '1'")
@opp_druid_losses = Match.where("opp_class = '1' AND outcome = '0'")
@opp_hunter_matches = Match.where("opp_class = '2'")
@opp_hunter_wins = Match.where("opp_class = '2' AND outcome = '1'")
@opp_hunter_losses = Match.where("opp_class = '2' AND outcome = '0'")
@opp_mage_matches = Match.where("opp_class = '3'")
@opp_mage_wins = Match.where("opp_class = '3' AND outcome = '1'")
@opp_mage_losses = Match.where("opp_class = '3' AND outcome = '0'")
@opp_paladin_matches = Match.where("opp_class = '4'")
@opp_paladin_wins = Match.where("opp_class = '4' AND outcome = '1'")
@opp_paladin_losses = Match.where("opp_class = '4' AND outcome = '0'")
@opp_priest_matches = Match.where("opp_class = '5'")
@opp_priest_wins = Match.where("opp_class = '5' AND outcome = '1'")
@opp_priest_losses = Match.where("opp_class = '5' AND outcome = '0'")
@opp_rogue_matches = Match.where("opp_class = '6'")
@opp_rogue_wins = Match.where("opp_class = '6' AND outcome = '1'")
@opp_rogue_losses = Match.where("opp_class = '6' AND outcome = '0'")
@opp_shaman_matches = Match.where("opp_class = '7'")
@opp_shaman_wins = Match.where("opp_class = '7' AND outcome = '1'")
@opp_shaman_losses = Match.where("opp_class = '7' AND outcome = '0'")
@opp_warlock_matches = Match.where("opp_class = '8'")
@opp_warlock_wins = Match.where("opp_class = '8' AND outcome = '1'")
@opp_warlock_losses = Match.where("opp_class = '8' AND outcome = '0'")
@opp_warrior_matches = Match.where("opp_class = '9'")
@opp_warrior_wins = Match.where("opp_class = '9' AND outcome = '1'")
@opp_warrior_losses = Match.where("opp_class = '9' AND outcome = '0'")
end
end
